language: python

python:
    - "2.7"

install:
    - python setup.py install
    - pip install --use-mirrors -r requirements.txt
    - pip install --use-mirrors -r requirements-test.txt

script:
  - rake lint
  - nosetests tests/unit tests/integration
